### ISSUE TITLE
Is this ready for release?

### ISSUE THREAD

**Issue by ghost** [BunsenLabs/bunsen-extras#1]
If yes, I would create a package and write a man page.

**Comment by johnraff** [comment]
No.
Its only content is BLOB which will be moved to **bunsen-utilities** soon. There's no reason for BLOB to be in a separate package now that its dependency _yad_ is in the regular repos. 

**bunsen-extras** was conceived as a package for scripts etc which depended on things which were only available from the backports, but until something else is put in it's just an empty holder.

btw is there a "clean" way to import a file from one git repo to another, beyond just copying it in?

PS but if you'd like to write a man page for BLOB to put in bunsen-utilities it would be most welcome!

**Comment by johnraff** [comment]
@capn-damo Is it OK if when moving this to bunsen-utilities I rename the executable from _blobthemes_ to _bl-obthemes_ to keep the bl- convention? bl-blobthemes seems a bit overdone...

**Comment by capn-damo** [comment]
Sounds reasonable. I just always kinda liked the "blob" thing!

**Comment by johnraff** [comment]
Yes agreed. 

It's only the executable name though. The script can still refer to itself as blobthemes.
