### ISSUE TITLE
Remove blobthemes from this repo, and rewrite README?

### ISSUE THREAD

**Issue by johnraff** [BunsenLabs/bunsen-extras#3]
The purpose of **bunsen-extras** is to hold packages - mainly scripts - which require packages from the _backports_ repositories (BunsenLabs or Debian) to work.

Now **yad** is in the _bunsen-hydrogen_ repo and _bl-obthemes_ has been incorporated into **bunsen-utilities** I think we should remove blobthemes from here, and rewrite README to indicate that this repo is now just a placeholder for something than might be added later.

Does this sound reasonable?

**Comment by capn-damo** [comment]
Certainly

**Comment by johnraff** [comment]
Finally done!
